### ISSUE TITLE
See the question correctly you have not solved properly

### ISSUE THREAD

**Issue by zaidhafeez** [sohail1613/DSA_questions#3]
[https://github.com/sohail1613/DSA_questions/blob/main/src/com/company/Basic/Q8_SubtractProductSum.java](url)

you have to give a number and find the sum of individual digits of number and similarly for the product too.
e.g. number = 123
sum = 1+2+3 = 6
product = 1*2*3 = 6

**Comment by sohail1613** [comment]
Solved accordingly

**Comment by zaidhafeez** [comment]
can you please attach the answer

**Comment by sohail1613** [comment]
> can you please attach the answer
Here it is
https://github.com/sohail1613/DSA_questions/blob/main/src/com/company/Basic/Q8_SubtractProductSum.java
