### ISSUE TITLE
Solve it without using any third variable

### ISSUE THREAD

**Issue by zaidhafeez** [sohail1613/DSA_questions#5]
[src/com/company/Basic/Q20_SwapNumbers.java](url)

**Comment by sohail1613** [comment]
Solved 
using two variables only

**Comment by zaidhafeez** [comment]
Please attach the link of answer when you are closing the issue

**Comment by sohail1613** [comment]
> Please attach the link of answer when you are closing the issue

https://github.com/sohail1613/DSA_questions/blob/main/src/com/company/Basic/Q5_FibonacciSeries.java
